kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
data:
  example.property.1: hello
  example.property.2: world
  application.properties: |-
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=spring-boot-username
    spring.datasource.password=spring-boot-password
